INSERT INTO main.actions ("action") VALUES ('Follow URL');
INSERT INTO main.actions ("action") VALUES ('Follow User');
INSERT INTO main.actions ("action") VALUES ('Get Favorites');
INSERT INTO main.actions ("action") VALUES ('Get Followers');
INSERT INTO main.actions ("action") VALUES ('Get Following');
INSERT INTO main.actions ("action") VALUES ('Get RT by User');
INSERT INTO main.actions ("action") VALUES ('Get RT to User');
INSERT INTO main.actions ("action") VALUES ('Get User Information');
INSERT INTO main.actions ("action") VALUES ('Mark Favorite');
INSERT INTO main.actions ("action") VALUES ('Unmark Favorite');
INSERT INTO main.actions ("action") VALUES ('Added New Account');
INSERT INTO main.actions ("action") VALUES ('Sign In With Twitter');
INSERT INTO main.actions ("action") VALUES ('Save Settings');
INSERT INTO main.actions ("action") VALUES ('RT Without Comment');
INSERT INTO main.actions ("action") VALUES ('Direct Message');
INSERT INTO main.actions ("action") VALUES ('Tweet');
INSERT INTO main.actions ("action") VALUES ('RT With Comment');
INSERT INTO main.actions ("action") VALUES ('Unfollow User');
INSERT INTO main.actions ("action") VALUES ('Delete User');
INSERT INTO main.actions ("action") VALUES ('Get Trends');
INSERT INTO main.actions ("action") VALUES ('Search Tweets');
INSERT INTO main.actions ("action") VALUES ('URL Shortener');
INSERT INTO main.actions ("action") VALUES ('Advertisement');
INSERT INTO main.actions ("action") VALUES ('Feeds');
